sudo: required

services:
- docker

script:
- "./build.sh"

env:
  global:
    secure: w0jXCXLVgf08TDDEHfDuzWqNbDrwvJ4IF0dnSRseKetyUk7aQf/c36MsHrBIOLFBtUMhyxynhXbEhs7tDDopOACHcnXzHVpuoy2d4sCnawxNgQwvNYwe8u+qk3gpi+7i6hwu4tdz9QGqCKipa5F6xVAu4mRyqn6P1qY2V1/89AvjpNtN3kJHAyHKqy+y17KPsBxYHoPh9fgqg4OTQoBuky6PPK5XxZBUB9G/25y1LdNWC7JzghPhx4BR6riu1plmMZS7mRgDzeDI5bSzONHoJakugoSgBW1oOx9aWjOAH3KCS9BiqzJsKF2k4V6D0fk9qtPDqoxCDzW5NsE6zek2iWdpfpK5sB+8w3YjJzT/e1AuY2YLknc5VXF4QLlzveYESQ4zrLFVlgbKux3TPdLN6lkOg4/D8mDL9RgTb1UUY71Dt/agg2pj/A83ybbFcMaUf7gKt7G4eUr+h/i/o6ovn07EWWLXZJbrkSGnM3TIcQoltWTuAdj+6Hx15YYUhpBb2wkrHSGnev7rPyE7rUZ2DMZTyLTn2ncWMUiuCHeUlQYUSL8oYMIzl90ffdbVeZ/cSkBcVkpRuE9ZpzGQy/iyyEY2SC8UeFxdyD1I+iPz5l2vkPVaFi4m08ePq7f2RdDNI2lZzioQijK0hG3TbO59FCUZ257qd4MK5py0JV5HQJg=
